title: My freakin' awesome tutorial site
author: David Miller
email: dmiller2718@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This a website being developed as part of the Github Learning Lab Pages tutorial.

# social links
twitter_username: dmiller2718 # DO NOT include the @ character, or else the build will fail!
github_username:  dmiller # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
